-- 2025-01-21 not sure if this is that useful.
return {
	-- "ribelo/taskwarrior.nvim",
	-- opts = {
	-- 	-- your configuration comes here
	-- 	-- or leave it empty to use the default settings
	-- 	-- refer to the configuration section below
	-- },
	-- -- or
	-- config = true,
	-- keys = {
	-- 	{
	-- 		"<leader>td",
	-- 		desc = "Taskwarrior",
	-- 	},
	-- 	{
	-- 		"<leader>ftd",
	-- 		function()
	-- 			require("taskwarrior_nvim").browser({ "ready" })
	-- 		end,
	-- 		desc = "Ongoing tasks",
	-- 		mode = "n",
	-- 		noremap = true,
	-- 	},
	-- },
}
