function le --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LE_OPTIONS' --wraps='eza $EXA_STANDARD_OPTIONS $EXA_LE_OPTIONS' --description 'alias le eza $EXA_STANDARD_OPTIONS $EXA_LE_OPTIONS'
    eza $EXA_STANDARD_OPTIONS $EXA_LE_OPTIONS $argv
end
