function lg --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LG_OPTIONS' --wraps='eza $EXA_STANDARD_OPTIONS $EXA_LG_OPTIONS' --description 'alias lg eza $EXA_STANDARD_OPTIONS $EXA_LG_OPTIONS'
    eza $EXA_STANDARD_OPTIONS $EXA_LG_OPTIONS $argv
end
