function loaai --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LAAI_OPTIONS $EZA_LO_OPTIONS' --wraps='eza $EXA_STANDARD_OPTIONS $EXA_LAAI_OPTIONS $EXA_LO_OPTIONS' --description 'alias loaai eza $EXA_STANDARD_OPTIONS $EXA_LAAI_OPTIONS $EXA_LO_OPTIONS'
  eza $EXA_STANDARD_OPTIONS $EXA_LAAI_OPTIONS $EXA_LO_OPTIONS $argv
        
end
