function lod --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LD_OPTIONS $EZA_LO_OPTIONS' --wraps='eza $EXA_STANDARD_OPTIONS $EXA_LD_OPTIONS $EXA_LO_OPTIONS' --description 'alias lod eza $EXA_STANDARD_OPTIONS $EXA_LD_OPTIONS $EXA_LO_OPTIONS'
    eza $EXA_STANDARD_OPTIONS $EXA_LD_OPTIONS $EXA_LO_OPTIONS $argv
end
