function lti --wraps='eza $EZA_STANDARD_OPTIONS $EZA_LI_OPTIONS $EZA_LT_OPTIONS' --wraps='eza $EXA_STANDARD_OPTIONS $EXA_LI_OPTIONS $EXA_LT_OPTIONS' --description 'alias lti eza $EXA_STANDARD_OPTIONS $EXA_LI_OPTIONS $EXA_LT_OPTIONS'
  eza $EXA_STANDARD_OPTIONS $EXA_LI_OPTIONS $EXA_LT_OPTIONS $argv
        
end
