" Davy Jones vimrc
" Updated 2/4/2018
" Plugins Used {{{
" NERD Commenter - for code commenting
" CTRL P         - for fuzzy searching
" NerdTree       - for Directory Viewing
" vim-go         - For Go Development
" Syntastic      - for Syntactic checking
" Airline        - For status bar
" }}}
" Basic Options {{{
runtime! debian.vim
runtime macros/matchit.vim
filetype off
set nocompatible           " make vim act like vim, not vi
set laststatus=2           " another status line so that airline will work
set number                 " enable line numbers
set relativenumber         " use relative line numbers
set showcmd                " show command at bottom of screen
set wildmenu               " helpful command completion with <TAB>
set showmatch              " show matching brackets etc
set ignorecase		         " Do case insensitive matching
set noshowmode             " don't show insert at bottom
set ttyfast                " improves smoothness
set wrap linebreak nolist  " wrap on words so their not broken
set ttimeoutlen=0          " Improve mode shifting speed
let mapleader=","          " change leader key to comma

if &term =~ '256color'
      " Disable Background Color Erase (BCE) so that color schemes work
      " properly within 256-color terminals
      set t_ut=
endif

" }}}
" Colours {{{
set t_Co=256
set encoding=utf-8
syntax on
filetype plugin indent on
set background=dark
" colorscheme tender      " Use terminal colour scheme
" }}}
" Key Mapping {{{
let g:ctrlp_map = '<c-p>'  " map CTRL+P to ctrlP for fuzzy searching
let g:ctrlp_cmd = 'CtrlP'  " map CTRL+P to ctrlP for fuzzy searching
" paste from clipboard on new line
map <leader>p :set paste<CR>o<esc>"*]p:set nopaste<cr> 
" set spellcheck on/off
map <leader>son :setlocal spell spelllang=en_gb<cr>
map <leader>soff :set nospell<cr>
" goto file in new window
map gf <c-w>gf
map <leader>nt :tabnew<cr>
" remap increment and decrement numbers to Alt
:nnoremap å <C-a>
:nnoremap ≈ <C-x>
" stop fighting spelling mistakes
:command WQ wq
:command Wq wq
:command W w
:command Q q
" move around panes faster
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
noremap <C-h> <C-w>h
" save faster  
map <leader>q :q<cr>
noremap Z <Esc>:w<CR>
noremap ZZ <Esc>:wq<CR>
" Go-Vim commands
au FileType go nmap <Leader>gd <Plug>(go-doc-tab)
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)
au FileType go nmap <Leader>gi <Plug>(go-imports)
" Custom Stuff
:command Date pu=strftime('%d-%m-%Y %H:%M')
:command DDiff w !diff % -
:cmap w!! w !sudo tee > /dev/null   
" }}} 
" Tab {{{
set tabstop=2     " tab == 2 spaces
set softtabstop=2
set shiftwidth=2
set expandtab     " tabs are spaces
" }}}
" Searching {{{
set incsearch     " highlight when searching
set hlsearch      " highlight all matches on search
nmap <leader>h :nohlsearch<cr>
" }}} 
" Window Configuration {{{
set splitbelow
set splitright
set winwidth=84
set winheight=5
set winminheight=5
set winheight=999
" }}}
" Folding {{{
set foldmethod=indent   " fold based on indent level
set foldnestmax=10      " max 10 depth
set foldenable          " don't fold files by default on open
nnoremap <TAB> za       
set foldlevelstart=10   " start with fold level of 1
set modelines=1
" }}}
" NerdTree {{{
let g:NERDTreeWinSize=18 
" }}}
" NerdCommenter {{{
let g:NERDSpaceDelims = 1       " Add 1 space after comment delimiter
let g:NERDCompactSexyComs = 1   " Use compact style for multi lines
let g:NERDDefaultAlign = 'left' " Don't follow TABS when commenting
" }}}
" Airline {{{
let g:airline_powerline_fonts = 1
let g:airline_theme = 'violet'
" }}}
" Backups {{{
set backup 
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp 
set backupskip=/tmp/*,/private/tmp/* 
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp 
set writebackup
" }}}
" Startup Functions {{{
function! StartUp()
   if 0 == argc()
     NERDTree
   end
endfunction

autocmd VimEnter * call StartUp()
set directory^=$HOME/.vim/swap//
" }}}
" vim:foldmethod=marker:foldlevel=0
