# -- Visual -------------------------------------------------------------------

run '~/.config/tmux/plugins/catppuccin-tmux/catppuccin.tmux'

set -g @catppuccin_flavour 'mocha'

## Start window indexing from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g allow-rename off
set-option -g automatic-rename off
set-option -g default-shell /bin/zsh

set-option -sg escape-time 10

set-option -g default-terminal 'tmux-256color'
set-option -g terminal-overrides ',tmux-256color:RGB'

# Status Bar
set -g @catppuccin_pane_default_text "#W"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W#{?window_zoomed_flag, 󰊓,}"
set -g @catppuccin_window_default_text " #W"
set -g status-right-length 100
set -g status-left-length 101
set -g status-interval 5
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#[fg=#89b4fa,bg=#313244]#[fg=#1e1e2e,bg=#89b4fa] 󱃾 #[fg=#cdd6f4,bg=#313244] #(kubectl config current-context 2>/dev/null | sed 's|.*/||' | cut -c1-30) "

set -g @pomodoro_on " 🟡"
set -g @pomodoro_complete " 🟢"
set -g @pomodoro_pause " ⏸︎"

# -- Monitoring ---------------------------------------------------------------

# Monitor activity in windows
setw -g monitor-activity on
set -g visual-activity off  # Don't show tmux's own message
set -g activity-action other  # Only notify for other windows

# Send bell on activity
set -g bell-action any
set -g visual-bell off

# -- Navigation ---------------------------------------------------------------

set -g mouse on                   # enable mouse support
set-window-option -g mode-keys vi # use vi keys
set -s escape-time 10             # faster command sequences
set -sg repeat-time 600           # increase repeat timeout
set -s focus-events on
set -g status-right-length 100

# -- Key Bindings -------------------------------------------------------------

## Remap prefix to C-a
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
bind l send-keys 'C-l'

## simple session picker
bind-key S choose-session

## maximise a pane
bind z resize-pane -Z

## Use vi keys for selection
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

## Open panes in current dir
bind "-" split-window -v -c "#{pane_current_path}"
bind "|" split-window -h -c "#{pane_current_path}"

## Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

## Floating Terminal
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'blue'
set -g @floax-change-path 'true'
set -g @floax-bind '-n M-t'

## -- tmux thumbs
set -g @thumbs-key /

# -- Plugins ------------------------------------------------------------------

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'olimorris/tmux-pomodoro-plus'

run-shell ~/.tmux/plugins/tmux-thumbs/tmux-thumbs.tmux

run '~/.tmux/plugins/tpm/tpm'
