name: dev
root: ~/

windows:
  - editor:
      root: ~/go/src/github.com/einride
      layout: main-horizontal
      panes:
        - vi
  - shell:
      layout: tiled
      panes:
        -
        -
  - notes:
      root: "~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/umo"
      layout: main-horizontal
      panes:
        - vi
        -
