name: dev
root: ~/
tmux_options: "-u"

windows:
  - work:
      root: "~/go/src/github.com/feverenergy/"
      layout: tiled
      panes:
        -
  - other:
      layout: main-horizontal
      panes:
        -
        -
  - db:
      layout: 81e7,382x65,0,0[382x59,0,0,2,382x5,0,60,13
      panes:
        - vi -c :DBUI
        - ssh -v -N sandbox-jump
  - notes:
      root: "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/notes"
      layout: even-vertical
      panes:
        - vi
        - ttoday
  - config:
      root: "~/dotfiles/.config/"
      layout: tiled
      panes:
        - vi

  - learn:
      root: "~/go/src/github.com/davyj0nes/micro_toys/"
      layout: tiled
      panes:
        - vi
