name: dev
root: ~/
tmux_options: "-u"

windows:
  - editor:
      root: ~/go/src/github.com/einride
      layout: main-horizontal
      panes:
        -
        -
  - shell:
      layout: tiled
      panes:
        -
        -
  - notes:
      root: '~/Library/Mobile Documents/iCloud~md~obsidian/Documents/notes'
      layout: even-vertical
      panes:
        - vi
        - ttoday
  - config:
      root: "~/.config/"
      layout: tiled
      panes:
        - vi
