name: dev
root: ~/
tmux_options: "-u"

windows:
  - editor:
      root: ~/go/src/github.com/einride
      layout: main-horizontal
      panes:
        -
  - shell:
      layout: tiled
      panes:
        -
        -
  - notes:
      root: "~/notes"
      layout: main-horizontal
      panes:
        - vi
        -
  - config:
      root: "~/.config/"
      layout: main-horizontal
      panes:
        -
