" Davy Jones vimrc v3

" General {{{
execute pathogen#infect()
runtime! debian.vim
runtime macros/matchit.vim
set nocompatible
filetype off
syntax on
filetype plugin indent on
set formatoptions=tcqrn1
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround
set ttyfast
set laststatus=2
set showmode
set showcmd
set matchpairs+=<:>
set nowrap
set number                 " enable line numbers
set relativenumber         " use relative line numbers
set wildmenu               " helpful command completion with <TAB>
set title
let mapleader=","          " change leader key to comma
set t_Co=256
set encoding=utf-8
set background=dark

" Hardcore mode, disable arrow keys.
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

if &term =~ '256color'
      " Disable Background Color Erase (BCE) so that color schemes work
      " properly within 256-color terminals
      set t_ut=
endif
" }}}

" Helpers {{{
" stop fighting spelling errors
:command WQ wq
:command Wq wq
:command W w
:command Q q

" move around panes faster
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
noremap <C-h> <C-w>h

" tabs
map <leader>tt :tabnew<cr>
map <leader>tc :tabc<cr>

" save faster  
map <leader>q :q<cr>
noremap Z <Esc>:w<CR>
noremap ZZ <Esc>:wq<CR>

" set spellcheck on/off
map <leader>son :setlocal spell spelllang=en_gb<cr>
map <leader>soff :set nospell<cr>

let g:ctrlp_map = '<c-p>'  " map CTRL+P to ctrlP for fuzzy searching
let g:ctrlp_cmd = 'CtrlP'  " map CTRL+P to ctrlP for fuzzy searching
" paste from clipboard on new line
map <leader>p :set paste<CR>o<esc>"*]p:set nopaste<cr> 

" remap increment and decrement numbers to Alt
:nnoremap å <C-a>
:nnoremap ≈ <C-x>

:command Date pu=strftime('%d-%m-%Y %H:%M')
:command DDiff w !diff % -
:cmap w!! w !sudo tee > /dev/null   

set incsearch     " highlight when searching
set hlsearch      " highlight all matches on search
nmap <leader>h :nohlsearch<cr>
" }}}

" Window Configuration {{{
set splitbelow
set splitright
set winwidth=84
set winheight=5
set winminheight=5
set winheight=999

set colorcolumn=80
hi ColorColumn ctermbg=darkgrey
" }}}

" Plugin Configuration {{{
" airline
let g:airline_theme='bubblegum'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_go_checkers = ['go vet']

" nerdtree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" nerdcommenter
let g:NERDSpaceDelims = 1       " Add 1 space after comment delimiter
let g:NERDCompactSexyComs = 1   " Use compact style for multi lines
let g:NERDDefaultAlign = 'left' " Don't follow TABS when commenting

" Go-Vim 
au FileType go nmap <Leader>gd <Plug>(go-doc-tab)
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)
au FileType go nmap <Leader>gi <Plug>(go-imports)

let g:go_fmt_autosave = 1
let g:go_fmt_command = "goimports"
let g:go_auto_type_info = 1

" mkdx
let g:mkdx#settings     = { 'highlight': { 'enable': 1 },
                        \ 'enter': { 'shift': 1 },
                        \ 'links': { 'external': { 'enable': 1 } },
                        \ 'toc': { 'text': 'Table of Contents', 'update_on_write': 1 },
                        \ 'fold': { 'enable': 1 } }

let g:polyglot_disabled = ['markdown'] " for vim-polyglot users, it loads Plasticboy's markdown
                                       " plugin which unfortunately interferes with mkdx list indentation.

" hashivim
let g:terraform_align=1
let g:terraform_fmt_on_save=1
" }}}

" Folding {{{
set foldmethod=indent   " fold based on indent level
set foldnestmax=10      " max 10 depth
set foldenable          " don't fold files by default on open
nnoremap <TAB> za       
set foldlevelstart=10   " start with fold level of 1
set modelines=1
" }}}

" Backups {{{
set backup 
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp 
set backupskip=/tmp/*,/private/tmp/* 
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp 
set writebackup
" }}}

" vim:foldmethod=marker:foldlevel=0
